###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: projeto-src-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=src
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=projeto-src
      ports:
        - "8004:5432"

    webserver:
      image: nginx:alpine
      container_name: projeto-src-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: projeto-src-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

